Particular/NServiceBus.Callbacks

- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/packages.config
- src/NServiceBus.Callbacks/IncomingContextExtensions.cs
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
- src/NServiceBus.Callbacks/RequestResponseInvocationForControlMessagesBehavior.cs
- src/NServiceBus.Callbacks/RequestResponseInvocationForMessagesBehavior.cs
- src/NServiceBus.Callbacks/SetCallbackResponseReturnCodeBehavior.cs
- src/NServiceBus.Callbacks/SkipBestPracticesForReplyIntEnumBehavior.cs
- src/NServiceBus.Callbacks/UpdateRequestResponseCorrelationTableBehavior.cs
- src/NServiceBus.Callbacks/packages.config
update to latest unstable core version which changed some behavior namespaces.
related to Particular/NServiceBus#3319
> update to latest v6 unstable

- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/packages.config
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks.Tests/packages.config
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
- src/NServiceBus.Callbacks/packages.config
@Particular/nservicebus-maintainers please review
> Update to unstable 1663

- packaging/nuget/nservicebus.callbacks.nuspec
- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/packages.config
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks.Tests/packages.config
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
- src/NServiceBus.Callbacks/packages.config
connects to https://github.com/Particular/PlatformDevelopment/issues/706
> update to beta 1 of core

- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks.Tests/UpdateRequestResponseCorrelationTableBehaviorTests.cs
- src/NServiceBus.Callbacks.Tests/When_sending_reply_to_the_request.cs
- src/NServiceBus.Callbacks.Tests/packages.config
- src/NServiceBus.Callbacks/ExtendableOptionsExtensions.cs
- src/NServiceBus.Callbacks/IncomingContextExtensions.cs
- src/NServiceBus.Callbacks/Reply/RequestResponseInvocationForControlMessagesBehavior.cs
- src/NServiceBus.Callbacks/Reply/RequestResponseInvocationForMessagesBehavior.cs
- src/NServiceBus.Callbacks/Request/UpdateRequestResponseCorrelationTableBehavior.cs
- src/NServiceBus.Callbacks/RequestResponseExtensions.cs
- src/NServiceBus.Callbacks/RequestResponseStateLookup.cs
Fixes #31 
PR is based on #30 
* Pulls in the testable contexts to reproduce the leak
* Fixes TODO in tests for `When_sending_reply_to_the_request`
* Addresses memory leak
* Fixes bug with `TrySetCanceled`
> Fix for Callback state leak

- packaging/nuget/nservicebus.callbacks.nuspec
- src/NServiceBus.Callbacks.AcceptanceTests/ConfigureEndpointMsmqTransport.cs
- src/NServiceBus.Callbacks.AcceptanceTests/EndpointTemplates/DefaultServer.cs
- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/ScenarioDescriptors/Transports.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_a_callback_for_local_message.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_a_callback_for_local_message_canceled.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_enum_response_canceled.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_int_response_canceled.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callback_to_get_message.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callback_to_get_message_canceled.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callbacks_in_a_scaleout.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callbacks_with_messageid_eq_cid.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_enum_response.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_enum_response_and_conventions.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_int_response.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_int_response_and_conventions.cs
- src/NServiceBus.Callbacks.AcceptanceTests/packages.config
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks.Tests/When_sending_reply_to_the_request.cs
- src/NServiceBus.Callbacks.Tests/packages.config
- src/NServiceBus.Callbacks/CallbackSupport.cs
- src/NServiceBus.Callbacks/IncomingContextExtensions.cs
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
- src/NServiceBus.Callbacks/Reply/RequestResponseInvocationForControlMessagesBehavior.cs
- src/NServiceBus.Callbacks/Reply/RequestResponseInvocationForMessagesBehavior.cs
- src/NServiceBus.Callbacks/Request/SkipBestPracticesForReplyIntEnumBehavior.cs
- src/NServiceBus.Callbacks/Request/UpdateRequestResponseCorrelationTableBehavior.cs
- src/NServiceBus.Callbacks/packages.config
@Particular/nservicebus-maintainers Please review and merge.
Connects to https://github.com/Particular/V6Launch/issues/65
> Update to NServiceBus 6.0.0-beta006

- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callback_to_get_message.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callback_to_get_message_canceled.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callbacks_in_a_scaleout.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callbacks_with_messageid_eq_cid.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_enum_response.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_enum_response_and_conventions.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_int_response.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_int_response_and_conventions.cs
- src/NServiceBus.Callbacks/CallbackSupport.cs
- src/NServiceBus.Callbacks/Reply/RequestResponseInvocationForControlMessagesBehavior.cs
- src/NServiceBus.Callbacks/Reply/RequestResponseInvocationForMessagesBehavior.cs
- src/NServiceBus.Callbacks/Reply/SetCallbackResponseReturnCodeBehavior.cs
- src/NServiceBus.Callbacks/Request/SkipBestPracticesForReplyIntEnumBehavior.cs
- src/NServiceBus.Callbacks/Request/UpdateRequestResponseCorrelationTableBehavior.cs
Connects to https://github.com/Particular/V6Launch/issues/3
@Particular/nservicebus-maintainers please review and merge
> Cleanup registrations

- packaging/nuget/nservicebus.callbacks.nuspec
- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/packages.config
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks.Tests/packages.config
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
- src/NServiceBus.Callbacks/packages.config
Connects to https://github.com/Particular/V6Launch/issues/3
@Particular/nservicebus-maintainers please review and merge
> Update to Core RC1

- GitVersion.yml
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
- src/NServiceBus.Callbacks/packages.config
Connects to https://github.com/Particular/V6Launch/issues/3
@Particular/nservicebus-maintainers please review and merge
> Update GitVersion 3.6.3

- src/NServiceBus.Callbacks.Tests/UpdateRequestResponseCorrelationTableBehaviorTests.cs
- src/NServiceBus.Callbacks/Request/UpdateRequestResponseCorrelationTableBehavior.cs
- src/NServiceBus.Callbacks/RequestResponseExtensions.cs
> Early cancellation

- src/NServiceBus.Callbacks.AcceptanceTests/ConfigureEndpointInMemoryPersistence.cs
- src/NServiceBus.Callbacks.AcceptanceTests/ConfigureEndpointMsmqTransport.cs
- src/NServiceBus.Callbacks.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
- src/NServiceBus.Callbacks.AcceptanceTests/EndpointTemplates/DefaultPublisher.cs
- src/NServiceBus.Callbacks.AcceptanceTests/EndpointTemplates/DefaultServer.cs
- src/NServiceBus.Callbacks.AcceptanceTests/EndpointTemplates/EndpointCustomizationConfigurationExtensions.cs
- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/packages.config
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks.Tests/packages.config
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
- src/NServiceBus.Callbacks/packages.config
relates to https://github.com/Particular/NServiceBus/pull/4377
> Update to core 6.1

- src/NServiceBus.Callbacks.Testing/TestableCallbackAwareSession.cs
- src/NServiceBus.Callbacks.Tests/UpdateRequestResponseCorrelationTableBehaviorTests.cs
- src/NServiceBus.Callbacks/RequestResponseExtensions.cs
- src/NServiceBus.Callbacks/TaskCompletionSourceAdapter.cs
> No longer use reflection in task completion source adapter

- src/Directory.Build.props
- src/NServiceBus.Callback.Testing.Tests/NServiceBus.Callback.Testing.Tests.csproj
- src/NServiceBus.Callbacks.Testing/NServiceBus.Callbacks.Testing.csproj
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
Adds SourceLink support a couple other misc things.
> More cleanup

- src/NServiceBus.Callbacks.AcceptanceTests/When_a_callback_for_local_message_canceled.cs
I've investigated #78 and it turns out that the flakiness came from the fact that if you cancel a callback and have no handlers present the core will throw
`System.InvalidOperationException : No handlers could be found for message type: NServiceBus.Callbacks.AcceptanceTests.When_a_callback_for_local_message_canceled+MyResponse`
See for more details: https://builds.particular.net/viewLog.html?buildId=241894&tab=buildResultsDiv&buildTypeId=NServiceBus_NServiceBus_Callbacks_32
I modified the test to have a handler for the response so that we can assert that we do get the response but that the callback doesn't fire. This solves the race condition and makes the test more accurate IMO.
@bording @danielmarbach thoughts?
Fixes #78
> Check that response message arrived when cancelling callbacks

- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks.Tests/TaskCompletionSourceAdapterTests.cs
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
- src/NServiceBus.Callbacks/TaskCompletionSourceAdapter.cs
- src/NServiceBus.Callbacks/TaskEx.cs
See https://github.com/Particular/NServiceBus.Callbacks/issues/92
> Callback continuation can block pipeline execution

- src/GitVersionWorkaround.targets
- src/NServiceBus.Callbacks.Testing/NServiceBus.Callbacks.Testing.csproj
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
Brings in a fixed GitVersionTask package.
> Update Particular.Packaging to 0.3.0

- .gitattributes
- src/GitVersionWorkaround.targets
- src/NServiceBus.Callbacks.Testing/NServiceBus.Callbacks.Testing.csproj
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
Brings in a fixed GitVersionTask package.
>  Update Particular.Packaging to 0.3.0

- GitVersion.yml
- src/NServiceBus.Callbacks.Testing/NServiceBus.Callbacks.Testing.csproj
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
> Update Particular.Packaging in release-3.0

- GitVersion.yml
- src/NServiceBus.Callbacks.Testing/NServiceBus.Callbacks.Testing.csproj
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
> Update Particular.Packaging in release-2.0

- GitVersion.yml
- src/NServiceBus.Callbacks.Testing/NServiceBus.Callbacks.Testing.csproj
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
> Update Particular.Packaging in master

- src/NServiceBus.Callback.Testing.Tests/NServiceBus.Callback.Testing.Tests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
For your review @mauroservienti
> Update test projects to netcoreapp3.1 in master

- src/NServiceBus.Callback.Testing.Tests/NServiceBus.Callback.Testing.Tests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
For your review @mauroservienti
> Update test projects to netcoreapp3.1 in release-3.0

- src/NServiceBus.Callback.Testing.Tests/NServiceBus.Callback.Testing.Tests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/TestHelperExtensions.cs
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
Change the service registrations to IServiceCollection APIs.
> Update core alpha

- src/NServiceBus.Callbacks.Testing/NServiceBus.Callbacks.Testing.csproj
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
Target framework update to netcoreapp2.1 as part of https://github.com/Particular/Exploration/issues/482
> target framework update

- src/Custom.Build.props
> Adding Custom.build.props for MinVer

- .github/workflows/ci.yml
- .github/workflows/release.yml
- src/Custom.Build.props
- src/NServiceBus.Callback.Testing.Tests/NServiceBus.Callback.Testing.Tests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.Testing/NServiceBus.Callbacks.Testing.csproj
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks.sln
- src/NServiceBus.Callbacks/IncomingContextExtensions.cs
- src/NServiceBus.Callbacks/NServiceBus.Callbacks.csproj
Downstream follow-up to [preparing for .NET 8](https://github.com/Particular/NServiceBus/pull/6810).
> Prepare repo for .NET 8

- src/NServiceBus.Callback.Testing.Tests/NServiceBus.Callback.Testing.Tests.csproj
- src/NServiceBus.Callback.Testing.Tests/TestablecallbackAwareSessionTests.cs
- src/NServiceBus.Callbacks.AcceptanceTests/NServiceBus.Callbacks.AcceptanceTests.csproj
- src/NServiceBus.Callbacks.AcceptanceTests/When_a_callback_for_local_message.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_a_callback_for_local_message_canceled.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_controlmessage_response_does_not_match_expected_type.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_enum_response_canceled.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_int_response_canceled.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_message_response_does_not_match_expected_type.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callback_to_get_message.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callback_to_get_message_canceled.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callbacks_in_a_scaleout.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_callbacks_with_messageid_eq_cid.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_enum_response.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_enum_response_and_conventions.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_int_response.cs
- src/NServiceBus.Callbacks.AcceptanceTests/When_using_int_response_and_conventions.cs
- src/NServiceBus.Callbacks.Tests/NServiceBus.Callbacks.Tests.csproj
- src/NServiceBus.Callbacks.Tests/UpdateRequestResponseCorrelationTableBehaviorTests.cs
- src/NServiceBus.Callbacks.Tests/When_sending_reply_to_the_request.cs
This PR contains all changes related to assertion model according to the [constraint assertion model](https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertion-models/constraint.html).
Using a script, we apply all [assertion rules](https://docs.nunit.org/articles/nunit-analyzers/NUnit-Analyzers.html#assertion-rules-nunit2001---) provided by the NUnit.Analyzers package. In addition, some manual interventions are done when applicable.
> Migrate NUnit assertions to the constraint model in preparation of the NUnit 4 upgrade
